try{
    console.log(10/0);
} catch (error){
    console.log(error);
} finally {
    console.log("finished");
}
